version: '3.8'

services:
  nginx:
    image: docker.io/nginx:alpine
    volumes:
      - ./nginx.mypeeps.conf:/etc/nginx/nginx.conf
    ports: 
      - ${EXTERNAL_PORT}:80
    networks:
      - main
    depends_on:
      - django
      
  timescaledb:
    image: docker.io/timescale/timescaledb:latest-pg13
    environment:
      - POSTGRES_PASSWORD=mypeeps
    volumes: 
      - timescaledb_volume:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: ${DB_CPU}
    networks:
      - main

  pgpool:
    image: docker.io/bitnami/pgpool:4
    environment:
      - PGPOOL_BACKEND_NODES=0:timescaledb:5432
      - PGPOOL_SR_CHECK_USER=postgres
      - PGPOOL_SR_CHECK_PASSWORD=mypeeps
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=mypeeps
      - PGPOOL_ADMIN_USERNAME=postgres
      - PGPOOL_ADMIN_PASSWORD=mypeeps
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
      - PGPOOL_POSTGRES_CUSTOM_USERS=postgres
      - PGPOOL_POSTGRES_CUSTOM_PASSWORDS=mypeeps
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: ${PG_CPU}
    networks:
      - main

  redis:
    image: docker.io/redis:alpine
    deploy:
      resources:
        limits:
          cpus: ${REDIS_CPU}
    networks:
      - main

  django: 
    build: .
    environment:
      - PORT=8000
    volumes: 
      - .:/app/
    depends_on:
      - pgpool
      - timescaledb
      - redis
    deploy:
      resources:
        limits:
          cpus: ${DJANGO_CPU}
      mode: replicated
      replicas: ${DJANGO_REPLICAS}
    networks:
      - main

networks:
  main:

volumes:
  timescaledb_volume: