version: '3.2'
services:
    timescaledb:
      image: "timescale/timescaledb:latest-pg13"
      ports:
        - 5432:5432
      environment:
        - POSTGRES_PASSWORD=mypeeps
      volumes: 
        - timescaledb_volume:/var/lib/postgresql/data
    redis:
      image: "redis:alpine"
      ports: 
        - 6379:6379
    django: 
      build: .
      environment:
        - PORT=8000
      ports: 
        - 8000:8000
      volumes: 
        - django_src:/app/

volumes:
  django_src:
  timescaledb_volume: