version: '3.7'
services:
    timescaledb:
      image: "timescale/timescaledb:latest-pg13"
      ports:
        - 5432:5432
      environment:
        - POSTGRES_PASSWORD=mypeeps
    redis:
      image: "redis:alpine"
      ports: 
        - 6379:6379