# Generated by Django 4.2.5 on 2023-10-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peeps",
            name="name",
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
