# Generated by Django 4.2.5 on 2023-10-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_peeps_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="peeps",
            name="seed",
            field=models.CharField(
                blank=True, editable=False, max_length=128, unique=True
            ),
        ),
    ]
