# Generated by Django 4.2.5 on 2023-10-03 21:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0004_alter_peeps_seed"),
    ]

    operations = [
        migrations.AddField(
            model_name="peeps",
            name="users",
            field=models.ManyToManyField(
                related_name="users", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
