# Generated by Django 4.2.5 on 2023-10-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_peeps_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="peeps",
            name="age",
            field=models.SmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="peeps",
            name="hp",
            field=models.SmallIntegerField(default=100, editable=False),
        ),
    ]
