# Generated by Django 4.2.5 on 2023-10-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_peeps_age_peeps_hp"),
    ]

    operations = [
        migrations.AddField(
            model_name="peeps",
            name="attribute_creativity",
            field=models.SmallIntegerField(default=0, editable=False, max_length=5),
        ),
        migrations.AddField(
            model_name="peeps",
            name="attribute_romance",
            field=models.SmallIntegerField(default=0, editable=False, max_length=5),
        ),
    ]
