# Generated by Django 4.2.5 on 2023-10-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_peeps_attribute_creativity_peeps_attribute_romance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peeps",
            name="attribute_creativity",
            field=models.IntegerField(default=0, editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name="peeps",
            name="attribute_romance",
            field=models.IntegerField(default=0, editable=False, max_length=5),
        ),
    ]
