# Generated by Django 4.2.5 on 2023-10-04 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_peeps_attribute_creativity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peeps",
            name="attribute_creativity",
            field=models.SmallIntegerField(
                blank=True,
                editable=False,
                validators=[django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AlterField(
            model_name="peeps",
            name="attribute_romance",
            field=models.SmallIntegerField(
                blank=True,
                editable=False,
                validators=[django.core.validators.MaxValueValidator(5)],
            ),
        ),
    ]
