# Generated by Django 4.2.5 on 2023-10-05 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_alter_peeps_attribute_creativity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeepsMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(max_length=255)),
                ("hp", models.IntegerField()),
                ("attribute_creativity", models.FloatField()),
                ("attribute_romance", models.FloatField()),
                (
                    "peep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.peeps"
                    ),
                ),
            ],
        ),
    ]
